steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build based on the provided environment variable
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BUILD_ENV}" = "test" ]; then npm run build-test; fi
        if [ "${BUILD_ENV}" = "release" ]; then npm run build-release; fi
        if [ "${BUILD_ENV}" = "staging" ]; then npm run build-staging; fi
        if [ "${BUILD_ENV}" = "prod-beta" ]; then npm run build-beta; fi
        if [ "${BUILD_ENV}" = "prod" ]; then npm run build-prod; fi
        if [ "${BUILD_ENV}" = "prod-enterprise" ]; then npm run build-prod-enterprise; fi
        if [ "${BUILD_ENV}" = "prod-in" ]; then npm run build-prod-in; fi
        if [ "${BUILD_ENV}" = "prod-eu" ]; then npm run build-prod-eu; fi
        if [ "${BUILD_ENV}" = "prod-cn" ]; then npm run build-prod-cn; fi
        if [ -z "${BUILD_ENV}" ]; then npm run build-test; fi

# Specify the available environment variables
substitutions:
  _BUILD_ENV: 'test' # Default value, change as needed

# Cache configuration (optional, remove if not needed)
# cache:
#   paths:
#     - 'node_modules/**'
