steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the project based on the environment variable
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        case "${_BUILD_ENV}" in
          "test") npm run build-test ;;
          "release") npm run build-release ;;
          "staging") npm run build-staging ;;
          "prod-beta") npm run build-beta ;;
          "prod") npm run build-prod ;;
          "prod-enterprise") npm run build-prod-enterprise ;;
          "prod-in") npm run build-prod-in ;;
          "prod-eu") npm run build-prod-eu ;;
          "prod-cn") npm run build-prod-cn ;;
          *) npm run build-test ;;  # Default
        esac

  # Step 3: Deploy to Firebase Hosting using the official Firebase CLI
  - name: 'gcr.io/firebase/firebase-tools'  # Official Firebase CLI image
    args:
      - deploy
      - --only
      - hosting
      - --project
      - "${_FIREBASE_PROJECT_ID}"  # Use Firebase project ID

# Set the default logging behavior
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only

# Define environment variables for substitutions
substitutions:
  _BUILD_ENV: 'test'  # Default environment, change as needed
  _FIREBASE_PROJECT_ID: 'km-dev-434106'  # Replace with your actual Firebase project ID

# Optional cache configuration
# cache:
#   paths:
#     - 'node_modules/**'
