steps:
  - name: 'node:14'  # Use the appropriate Node.js version
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Build env:" $BUILD_ENV
        npm install
        echo "NPM install completed" | gcloud logging write build-log --severity=INFO

  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BUILD_ENV}" = "test" ]; then 
          npm run build-test; 
          echo "Build for test completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "release" ]; then 
          npm run build-release; 
          echo "Build for release completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "staging" ]; then 
          npm run build-staging; 
          echo "Build for staging completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod" ]; then 
          npm run build-prod; 
          echo "Build for production completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod-enterprise" ]; then 
          npm run build-prod-enterprise; 
          echo "Build for prod-enterprise completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod-in" ]; then 
          npm run build-prod-in; 
          echo "Build for prod-in completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod-eu" ]; then 
          npm run build-prod-eu; 
          echo "Build for prod-eu completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod-cn" ]; then 
          npm run build-prod-cn; 
          echo "Build for prod-cn completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ "${BUILD_ENV}" = "prod_beta" ]; then 
          npm run build-beta; 
          echo "Build for beta completed" | gcloud logging write build-log --severity=INFO; 
        fi
        if [ -z "${BUILD_ENV}" ]; then 
          npm run build-test; 
          echo "Default build for test completed" | gcloud logging write build-log --severity=INFO; 
        fi

# Optional: Define cache paths if needed
cache:
  paths:
    - 'node_modules/**/*'
    # - 'package-lock.json'

timeout: 1200s  # Adjust the timeout as needed
