name: Automate Common Checks

on: [pull_request]
jobs:
    pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@development
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install packages
              run: npm install
            - name: Danger
              run: npm run run-danger-test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
