name: Automate Common Checks

on: [pull_request]
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]
  
jobs:
    tasks:
        runs-on: ubuntu-latest
        steps: 
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install packages
              run: npm install
            - name: Danger
              run: npm run run-danger-test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
