name: Automate Common Checks Danger JS

on: 
    pull_request:
      branches:    
        - master
        - 'development'
jobs:
    PR_Test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out branch
            - uses: actions/checkout@master
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install packages
              run: npm install
            - name: Run Danger Test
              run: npm run run-danger-test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
